### ISSUE TITLE
Implement Commit-msg Hook

### ISSUE THREAD

**Issue by enveng-group** [enssol/web-app#19]
Set up a commit-msg hook to ensure commit messages follow a specific format or include necessary information.

**Comment by enveng-group** [comment]
@bwork005 I cannot review and close this issue without a pull request.

**Comment by bwork005** [comment]
Okay! I will make a pull request!

**Comment by bwork005** [comment]
Hi! I was doing the hooks in my own repo...Done with making few files. So I just had to copy and paste it into the web-app repo. But I can't find the .git folder. Even after using the git init command

**Comment by enveng-group** [comment]
> Hi! I was doing the hooks in my own repo...Done with making few files. So I just had to copy and paste it into the web-app repo. But I can't find the .git folder. Even after using the git init command @enveng-group

@bwork005 we will go through tomorrow morning in our stand-up. Did you try running `ls -a`?
